version: '3.7'

services:
  backend1:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:80 manage:app
    expose:
      - 80
    env_file:
      - ./.env.backend
    depends_on:
      - postgresql

  backend2:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:80 manage:app
    expose:
      - 80
    env_file:
      - ./.env.backend
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend1
      - backend2

volumes:
  postgres_data:
